import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        payabli: {
          cyan: "hsl(var(--payabli-cyan))",
          "cyan-light": "hsl(var(--payabli-cyan-light))",
          blue: "hsl(var(--payabli-blue))",
          slate: "hsl(var(--payabli-slate))",
          "slate-light": "hsl(var(--payabli-slate-light))",
        },
        status: {
          success: "hsl(var(--status-success))",
          "success-bg": "hsl(var(--status-success-bg))",
          "success-border": "hsl(var(--status-success-border))",
          "success-text": "hsl(var(--status-success-text))",
          warning: "hsl(var(--status-warning))",
          "warning-bg": "hsl(var(--status-warning-bg))",
          "warning-border": "hsl(var(--status-warning-border))",
          "warning-text": "hsl(var(--status-warning-text))",
          danger: "hsl(var(--status-danger))",
          "danger-bg": "hsl(var(--status-danger-bg))",
          "danger-border": "hsl(var(--status-danger-border))",
          "danger-text": "hsl(var(--status-danger-text))",
          info: "hsl(var(--status-info))",
          "info-bg": "hsl(var(--status-info-bg))",
          "info-border": "hsl(var(--status-info-border))",
          "info-text": "hsl(var(--status-info-text))",
          purple: "hsl(var(--status-purple))",
          "purple-bg": "hsl(var(--status-purple-bg))",
          "purple-text": "hsl(var(--status-purple-text))",
          watch: "hsl(var(--status-watch))",
          "watch-bg": "hsl(var(--status-watch-bg))",
          "watch-border": "hsl(var(--status-watch-border))",
          "watch-text": "hsl(var(--status-watch-text))",
        },
        ai: {
          DEFAULT: "hsl(var(--ai-accent))",
          bg: "hsl(var(--ai-accent-bg))",
          border: "hsl(var(--ai-accent-border))",
          text: "hsl(var(--ai-accent-text))",
        },
        insight: {
          bg: "hsl(var(--insight-bg))",
          border: "hsl(var(--insight-border))",
          text: "hsl(var(--insight-text))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "pulse-dot": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.4" } },
        "slide-in": { from: { opacity: "0", transform: "translateX(10px)" }, to: { opacity: "1", transform: "translateX(0)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-dot": "pulse-dot 1s infinite",
        "slide-in": "slide-in 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
